version: 2.1

orbs:
  python: circleci/python@2.0.3

commands:
  early_return_for_forked_pull_requests:
    description: >-
      If this build is from a fork, stop executing the current job and return success.
      This is useful to avoid steps that will fail due to missing credentials.
    steps:
      - run:
          name: Early return if this build is from a forked PR
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "Nothing to do for forked PRs, so marking this step successful"
              circleci step halt
            fi

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          command: make test-ci
          name: Run tests, lint
      - store_test_results:
          path: tests/test-results
      - store_artifacts:
          path: tests/htmlcov
      - early_return_for_forked_pull_requests
      - run:
          command: |
            echo "BACKBLAZE_BUCKET=${TEST_BUCKET}" >> sample_app/sample_app/settings.env
            echo "BACKBLAZE_APPLICATION_KEY_ID=${TEST_BACKBLAZE_APPLICATION_KEY_ID}" >> sample_app/sample_app/settings.env
            echo "BACKBLAZE_APPLICATION_KEY=${TEST_BACKBLAZE_APPLICATION_KEY}" >> sample_app/sample_app/settings.env
            make run-sample-proj-on-django-5.1
            make run-sample-proj-on-django-5.0
            make run-sample-proj-on-django-4.2
            make run-sample-proj-on-django-3.2
          name: Sanity check with sample proj

workflows:
  main:
    jobs:
      - build-and-test
